services:
  Dueto.Api:
    container_name: DueTo.Api
    image: dueto.api
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dueto.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO_URI=mongodb://admin:password@DueTo_Database:27017/dueto?authSource=admin
    networks:
      - app-network
    depends_on:
      DueTo.Database:
        condition: service_healthy
  DueTo.Database:
    image: mongo
    container_name: DueTo_Database
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: dueto
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    
volumes:
  mongo_data:
    
networks:
  app-network:
    driver: bridge
