services:
  Dueto.Api:
    container_name: DueTo.Api
    image: dueto.api
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dueto.Api/Dockerfile
    environment:
      - MONGO_URI=mongodb://admin:password@DueTo.Database:27017/admin
    networks:
      - app-network
  DueTo.Database:
    image: mongo
    container_name: DueTo_Database
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/var/opt/mongo
    networks:
      - app-network

    
volumes:
  mongo_data:
    
networks:
  app-network:
    driver: bridge
